export const loginApi = {
  LOGIN_USER_REQUEST: "LOGIN_USER_REQUEST",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_ERROR: "LOGIN_USER_ERROR",
};

export const signInApi = {
  SIGNIN_USER_REQUEST: "SIGNIN_USER_REQUEST",
  SIGNIN_USER_SUCCESS: "SIGNIN_USER_SUCCESS",
  SIGNIN_USER_ERROR: "SIGNIN_USER_ERROR",
};

export const workerAndSurvey = {
  // workerDataApi
  GET_WORKER_DATA_REQUEST: "GET_WORKER_DATA_REQUEST",
  GET_WORKER_DATA_SUCCESS: "GET_WORKER_DATA_SUCCESS",
  GET_WORKER_DATA_ERROR: "GET_WORKER_DATA_ERROR",

  FETCH_WORKER_DATA_REQUEST: " FFETCH_WORKER_DATA_REQUEST",
  FETCH_WORKER_DATA_SUCCESS: "FETCH_WORKER_DATA_SUCCESS",
  FETCH_WORKER_DATA_ERROR: "FETCH_WORKER_DATA_ERROR",

  POST_WORKER_DATA_REQUEST: "POST_WORKER_DATA_REQUEST",
  POST_WORKER_DATA_SUCCESS: "POST_WORKER_DATA_SUCCESS",
  POST_WORKER_DATA_ERROR: "POST_WORKER_DATA_ERROR",

  //surveyDataApi
  GET_SURVEY_DATA_REQUEST: "GET_SURVEY_DATA_REQUEST",
  GET_SURVEY_DATA_SUCCESS: "GET_SURVEY_DATA_SUCCESS",
  GET_SURVEY_DATA_ERROR: "GET_SURVEY_DATA_ERROR",

  POST_SURVEY_DATA_REQUEST: "POST_SURVEY_DATA_REQUEST",
  POST_SURVEY_DATA_SUCCESS: "POST_SURVEY_DATA_SUCCESS",
  POST_SURVEY_DATA_ERROR: "POST_SURVEY_DATA_ERROR",

  FETCH_SURVEY_DATA_REQUEST: " FFETCH_SURVEY_DATA_REQUEST",
  FETCH_SURVEY_DATA_SUCCESS: "FETCH_SURVEY_DATA_SUCCESS",
  FETCH_SURVEY_DATA_ERROR: "FETCH_SURVEY_DATA_ERROR",
};

export const userDataApi = {
  //userDataApi
  FETCH_USER_DATA_REQUEST: "FETCH_USER_DATA_REQUEST",
  FETCH_USER_DATA_ERROR: " FETCH_USER_DATA_ERROR",
  FETCH_USER_DATA_SUCCESS: " FETCH_USER_DATA_SUCCESS",

  POST_USER_EDIT_DATA_REQUEST: "POST_USER_EDIT_DATA_REQUEST",
  POST_USER_EDIT_DATA_SUCCESS: "POST_USER_EDIT_DATA_SUCCESS",
  POST_USER_EDIT_DATA_ERROR: "POST_SUSER_EDIT_DATA_ERROR",

  POST_DELETE_DATA_REQUEST: "POST_DELETE_DATA_REQUEST",
  POST_DELETE_DATA_SUCCESS: "POST_DELETE_DATA_SUCCESS",
  POST_DELETE_DATA_ERROR: "POST_DELETE_DATA_ERROR",

  // postDataForEditUser
  Edit_USER_DATA: " Edit_USER_DATA",

  DELETE_USER_DATA:"DELETE_USER_DATA"
};



export const FECTH_AVERAGE_WORKER_DATA_REQUEST = "FECTH_AVERAGE_WORKER_DATA_REQUEST"
export const FECTH_AVERAGE_WORKER_DATA_SUCCESS = "FECTH_AVERAGE_WORKER_DATA_SUCCESS"
export const FECTH_AVERAGE_WORKER_DATA_ERROR = "FECTH_AVERAGE_WORKER_DATA_ERROR"


export const FECTH_AVERAGE_WORKER_FROM_MAIN_DATA_REQUEST = "FECTH_AVERAGE_WORKER_FROM_MAIN_DATA_REQUEST"
export const FECTH_AVERAGE_WORKER_FROM_MAIN_DATA_SUCCESS = "FECTH_AVERAGE_WORKER_FROM_MAIN_DATA_SUCCESS"
export const FECTH_AVERAGE_WORKER_FROM_MAIN_DATA_ERROR = "FECTH_AVERAGE_WORKER_FROM_MAIN_DATA_ERROR"


// LODER CONTSTATNTS
export const SET_LOADING_TRUE = "SET_LOADING_TRUE"
export const SET_LOADING_FALSE = "SET_LOADING_FALSE"


export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_ERROR = "LOGOUT_ERROR"


